"""BriefBench results viewer — the paper's reported numbers (Streamlit + Plotly).

Reads the paper-sourced CSVs under ``results/data/`` (transcribed verbatim from the paper
"Depth, Not Length") and renders them as interactive tables and charts. These are the
paper's reported results, NOT regenerated by this repo's offline harness.

Run: ``streamlit run dashboard/app.py``.
Deploy free: push to GitHub -> share.streamlit.io -> point at dashboard/app.py.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "results" / "data"
BRIEF = "brief"
BLUE, GREY = "#1f77b4", "#c7c7c7"

st.set_page_config(page_title="BriefBench (paper results)", layout="wide", page_icon="📊")


@st.cache_data
def load(name: str) -> pd.DataFrame:
    """Load one paper-sourced CSV from results/data/ as a DataFrame."""
    path = DATA / name
    return pd.read_csv(path) if path.exists() else pd.DataFrame()


def bar_colors(systems: pd.Series) -> list[str]:
    """Highlight the Brief arm in blue, everything else grey."""
    return [BLUE if str(s).lower().startswith("brief") else GREY for s in systems]


realcode = load("paper_realcode_pooled.csv")
synthetic = load("paper_synthetic_compliance.csv")
slope = load("paper_depth_slope.csv")
supersession = load("paper_supersession.csv")
public = load("paper_public_benchmarks.csv")
tokens = load("paper_token_economics.csv")
scorecard = load("paper_scorecard.csv")
competitors = load("competitor_landscape.csv")
swe = load("swe_context_bench.csv")

st.title("Does product context make a coding agent better?")
st.markdown(
    "**The paper's reported results.** Every number here is transcribed verbatim from the "
    "paper *Depth, Not Length* (the source of truth) and is NOT regenerated by this repo's "
    "offline harness. Every arm sees the same model, budget, and tools; *memory "
    "architecture is the only variable* (the fairness lock)."
)

# ---------------- headline cards ----------------
if not realcode.empty:
    brief = realcode[realcode["arm"] == BRIEF].iloc[0]
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Real-code recall (Brief)", f"{brief['recall']:.3f}", "rank #1 (tab:realret)")
    c2.metric("Real-code compliance (Brief)", f"{brief['compliance']:.3f}", "rank #1")
    c3.metric("Use factor kappa (Brief)", f"{brief['kappa']:.3f}", "clears 0.56-0.64 band")
    c4.metric("Precision (Brief)", f"{brief['precision']:.3f}", "pooled dcbench+swebench")

tabs = st.tabs(
    [
        "🏆 Real code",
        "🧪 Synthetic",
        "📈 Depth slope",
        "🔁 Supersession",
        "🌐 Public benchmarks",
        "⚡ Token economics",
        "✅ Scorecard",
        "📚 Competitors",
    ]
)

with tabs[0]:
    st.subheader("Real-code retrieval and use, pooled (tab:realret)")
    st.caption(
        "Pooled dcbench + swebench, Claude. The typed store ranks first on recall and compliance."
    )
    if not realcode.empty:
        fig = px.bar(
            realcode.sort_values("compliance", ascending=False),
            x="arm",
            y="compliance",
            color="arm",
            color_discrete_sequence=bar_colors(
                realcode.sort_values("compliance", ascending=False)["arm"]
            ),
        )
        fig.update_layout(showlegend=False, yaxis_title="compliance P_comply")
        st.plotly_chart(fig, use_container_width=True)
        st.dataframe(realcode, use_container_width=True, hide_index=True)

with tabs[1]:
    st.subheader("Synthetic suite compliance by arm (tab:synthall)")
    if not synthetic.empty:
        ordered = synthetic.sort_values("compliance", ascending=False)
        fig = px.bar(
            ordered,
            x="arm",
            y="compliance",
            color="arm",
            color_discrete_sequence=bar_colors(ordered["arm"]),
        )
        fig.update_layout(showlegend=False, yaxis_title="compliance")
        st.plotly_chart(fig, use_container_width=True)
        st.dataframe(synthetic, use_container_width=True, hide_index=True)
    st.info(
        "hybrid_rrf and rerank_ce are not in tab:synthall; "
        "their per-depth values are in the depth-slope tab."
    )

with tabs[2]:
    st.subheader("Compliance depth slope, synthetic (tab:slope)")
    st.caption(
        "slope = comply(d3) - comply(d1). Brief decays least; "
        "the Brief-minus-best-similarity gap widens with depth."
    )
    if not slope.empty:
        st.dataframe(slope, use_container_width=True, hide_index=True)

with tabs[3]:
    st.subheader("Supersession: current-decision-ranked-first % (tab:super)")
    st.caption("Chance = 50%. Governance edges make 'prefer the current decision' a dereference.")
    if not supersession.empty:
        fig = px.bar(
            supersession,
            x="system",
            y="current_first_pct",
            color="system",
            color_discrete_sequence=bar_colors(supersession["system"]),
        )
        fig.add_hline(y=50, line_dash="dot", annotation_text="chance (50%)")
        fig.update_layout(showlegend=False, yaxis_title="current-first %")
        st.plotly_chart(fig, use_container_width=True)
        st.dataframe(supersession, use_container_width=True, hide_index=True)

with tabs[4]:
    st.subheader("Public benchmarks, unified harness (tab:stdbench / tab:t101pub)")
    st.caption(
        "Brief vs. the next-best system. Brief tops every row "
        "except HotpotQA supporting-fact recall."
    )
    if not public.empty:
        st.dataframe(public, use_container_width=True, hide_index=True)
    if not swe.empty:
        st.markdown(
            "**SWE-ContextBench leaderboard (tab:t070)** — Brief's row is modeled in the paper."
        )
        st.dataframe(swe, use_container_width=True, hide_index=True)

with tabs[5]:
    st.subheader("Token economics (tab:tok_context_winrate / by_competitor)")
    st.caption(
        "Brief is the cheaper session in 80.0% of 3,600 matchups "
        "(0 ties); 68.6%-86.7% per competitor."
    )
    if not tokens.empty:
        st.dataframe(tokens, use_container_width=True, hide_index=True)

with tabs[6]:
    st.subheader("Unbiased 41-axis scorecard (tab:scorecard)")
    if not scorecard.empty:
        fig = px.bar(scorecard, x="outcome", y="count", color="outcome", text="count")
        fig.update_layout(showlegend=False)
        st.plotly_chart(fig, use_container_width=True)
        st.dataframe(scorecard, use_container_width=True, hide_index=True)
    st.caption(
        "22 wins / 14 marginal (near-tie) / 5 losses. "
        "The 5 losses are kept and listed in results/EVALS.md."
    )

with tabs[7]:
    st.subheader("Competitive landscape (vendor-published, cited)")
    st.caption(
        "⚠️ Competitors' own published headline numbers (tab:landscape) — different "
        "benchmarks, NOT a controlled head-to-head."
    )
    if not competitors.empty:
        st.dataframe(competitors, use_container_width=True, hide_index=True)

st.divider()
st.caption(
    "Source of truth: the paper 'Depth, Not Length'. Honest scope: Brief leads on its "
    "design axes (real-code recall/use, depth, supersession, token economics) but loses 5 "
    "of 41 axes (e.g. HotpotQA supporting-fact recall to Zep) — reported straight. All "
    "numbers are the paper's reported results; nothing is regenerated by this repo."
)
